### PR TITLE
DOCS: add detailed setup instructions

### PR DESCRIPTION
**Pull request by rehmanis**
@Abdur-rahmaanJ I thought the instructions were not very clear so added another section. Should I remove the `How does the site gets built` section or keep it the way it it is?

### CODE REVIEW

**Comment by greyli** [comment]
> Should I remove the How does the site gets built section or keep it the way it it is?

Just remove it, I wanted to update this part yesterday as well. Good job!

**Comment by rehmanis** [comment]
> > Should I remove the How does the site gets built section or keep it the way it it is?
> 
> Just remove it, I wanted to update this part yesterday as well. Good job!

Thank @greyli. Any suggestions to improve it further or potential mistakes?

**Comment by greyli** [comment]
The command to activate the virtual environment on Windows should be `env\Scripts\activate`.

**Comment by rehmanis** [comment]
> The command to activate the virtual environment on Windows should be `env\Scripts\activate`.

fixed windows instructions. Merging.

**Pull request merged**
