### PR TITLE
LAYOUT: fix the website css styling

### LINKED ISSUE #43: Center site navigation bar
I've been trying to centre the navigation bar and I really couldn't find a way. @Abdur-rahmaanJ  I think you know a bit more about spectre.css so do you think you can do something?

### PR DESCRIPTION
**Pull request by rehmanis**
Fixes #43

* I moved the image from top to the right. If this does not feel natural, I can bring it back to the way it was (EDIT: go back to how it was before with image topmost)
* added the padding to all pages
* minor styles fixes

### CODE REVIEW

**Comment by rehmanis** [comment]
I also notice that even before this PR is merged, the changes in PR are already visible in the our deployed website https://flaskcwg.github.io/. Is this the expected behavior?

**Comment by Jalkhov** [comment]
@rehmanis Everything has been perfect, what doesn't convince me is the banner on the left, the idea was that it would work as the header of the site.

**Comment by rehmanis** [comment]
> @rehmanis Everything has been perfect, what doesn't convince me is the banner on the left, the idea was that it would work as the header of the site.

Yeah true. Another idea is we can replace the FlaskCWG link from navbar with the logo. Or move the logo below the navbar. Just felt that navbar should be top most but if it feels more natural to have the logo topmost then I can change it.

**Comment by Jalkhov** [comment]
> > @rehmanis Everything has been perfect, what doesn't convince me is the banner on the left, the idea was that it would work as the header of the site.
> 
> Yeah true. Another idea is we can replace the FlaskCWG link from navbar with the logo. Or move the logo below the navbar. Just felt that navbar should be top most but if it feels more natural to have the logo topmost then I can change it.

What happens is that it is a banner, not a logo, if we talk about a logo certainly if it would be nice where the brand goes (where it says FlaskCWG in the navbar), but at the same time I also feel that it would be like repeating again the image that is in the banner and although not tested, I think it would look weird, in any case, a possible solution would be to make a unicolor version of the logo and place it there, I think it would look good. I did a quick sketch in Photoshop and it certainly looks good, it's a good idea. You can do it if you want, otherwise I can pass you the logo in unicolour.

sample

**Comment by rehmanis** [comment]
@Jalkhov good points. So we keep the same top banner in this PR and then you can add the unicode if you like. In addition, I had to change the layout now that our image is top again. Here is how it looks. Its centered but not sure if that is what we are looking for. I added colored vs not colored images just to make it easier to see the centered aspect.
Colored:
color1
color2
color3

How it will:
nocolor1
nocolor2
nocolor3

**Comment by rehmanis** [comment]
Okay. I updated with image back to top. Let me know if I should rebase into one commit.

**Comment by Abdur-rahmaanJ** [comment]
The banner is cool. It was tested on mobile?

**Comment by Jalkhov** [comment]
> The banner is cool. It was tested on mobile?

It hides on mobiles, I couldn't make it responsive.

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov was only seeing if mobile is catered for

**Comment by rehmanis** [comment]
@Jalkhov oh no worries. If it look good then that's fine. I will let someone else merge if all is good.

**Pull request merged**
